-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE loanapp.amortization_schedule
(
    id integer NOT NULL,
    balance_owed double precision NOT NULL,
    interest_amount double precision NOT NULL,
    payment_amount double precision NOT NULL,
    payment_order integer NOT NULL,
    principal_amount double precision NOT NULL,
    loan_data_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE loanapp.loan_data
(
    id integer NOT NULL,
    amount double precision NOT NULL,
    interest_rate double precision NOT NULL,
    loan_term integer NOT NULL,
    monthly_payment double precision NOT NULL,
    term_type character(1) NOT NULL,
    total_interest double precision NOT NULL,
    total_payment double precision NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE loanapp.amortization_schedule
    ADD FOREIGN KEY (loan_data_id)
    REFERENCES loanapp.loan_data (id)
    NOT VALID;

END;